---

- name: Install Tools
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - python-mysqldb
  
- name: Update Hosts File
  synchronize: src=/etc/hosts dest=/etc/hosts

- name: Install MySQL-Server
  apt: name=mysql-server state=present update_cache=yes


- name: Ensure that MySQL is listening on eth0
  lineinfile: dest=/etc/mysql/my.cnf regexp=^bind-address
              line="bind-address = {{ ansible_eth1.ipv4.address }}"
  notify: Restart MySQL

- name: Ensure MySQL Server is started
  service: name=mysql state=started enabled=yes

- name: Create  Database
  mysql_db: name={{ db_name }} state=present
  
- name: Create Demo User
  mysql_user: name={{ db_user_name }} password={{ db_user_pass }} priv={{db_name }}.*:ALL 
              host='{{ db_user_host }}' state=present