---
- hosts: control
  become: true
  tasks:
    - name: Install Tools
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars: 
        packages:
        - curl
        - python-httplib2
