---
# Bring Down Stack

- hosts: loadbalancer
  become: true
  tasks: 
    - service: name=nginx state=stopped
    - wait_for: port=80 state=drained

- hosts: webservers
  become: true
  tasks:
    - service: name=apache2 state=stopped
    - wait_for: port=80 state=stopped

# Restart Database
- hosts: database
  become: true
  tasks:
    - service: name=mysql state=restarted
    - wait_for: port=3306 state=started

# Bring Up Stack
- hosts: webservers
  become: true
  tasks:
    - service: name=apache2 state=started
    - wait_for: port=80 state=started

- hosts: loadbalancer
  become: true
  tasks:
    - service: name=nginx state=started
    - wait_for: port=80 state=started
